### ISSUE TITLE
New verson

### ISSUE THREAD

**Issue by boster3218** [Podshot/MCEdit-Unified#1010]
This needs to work for newer versons of minecraft 1.16.2

**Comment by Podshot** [comment]
MCEdit-Unified will not be updated (by us) to support 1.13+ due to the numerous and significant changes in the Minecraft world format. However, we are working on a new editor named Amulet that can support both 1.12 worlds and worlds from 1.13 and above, you can learn more about it [here](https://www.amulet-editor.com/) and our Github repository is [here](https://github.com/Amulet-Team/Amulet-Map-Editor)
