### ISSUE TITLE
Cannot run 

### ISSUE THREAD

**Issue by Ygarr** [Podshot/MCEdit-Unified#1029]
```
"/usr/bin/MCEdit
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "/usr/lib/mcedit/mcedit.py", line 13, in <module>
    import splash
  File "/usr/lib/mcedit/splash.py", line 10, in <module>
    import pygame
ImportError: No module named pygame"
```

but 
```
community/python-pygame 2.1.1-1 (4.1 MiB 14.4 MiB) (Installed)
    Python game library
```

OS: Manjaro

**Comment by weirdal3333** [comment]
I get this on multiple distros of linux. I wish they provided binaries or at least included an already built environment. Not every package is available forever, guys! Just because you still use legacy dependencies doesn't mean everyone should need to install them.

**Comment by Khroki** [comment]
Yeah Python 2.7 support is getting pretty poor. Unfortunately PyGame is about as core a library as it could be and it's not really realistic to re-write the existing codebase without it. Your best bet is to compile PyGame yourself, which may or may not be realistic. (I handled OSX and Windows packaging when I was active and had to compile it myself for it to work on OSX .app releases) or use a OS release from a similar time to the last release that would have the package.

The bigger issue is really that this isn't under active development and the current developers have moved to Amulet as we felt a rewrite was necessary to continue to support newer versions due to core format changes in Minecraft and as Python 2.7 is obsoleted. I suspect due to that releases for Mac and Linux will eventually stop working without extra work if they haven't already. Classic case of software rot that just happens to affect Linux more severely due to it being an unfriendly environment for programs not under active development.

We had tried to make pre-packaged binaries like we did with OSX, but we had a lot of issues with cross-distro compatibility and had to abandon the idea.
